Click on class selection popup of layout tab with JavaScript
When we try to click on the div .cssclasswidget-overlay with "Click
Element", we get the error:

    ElementClickInterceptedException: Message: Element <div
class="cssclasswidget-overlay"> is not clickable at point (640,436)
because another element <li> obscures it

So, to be able to click on the div, we need to use javascript.