Fix RuntimeError when dropping an image from a list tile to a banner tile
In Python 3 it is not possible change dict size during iteration. So we
need to turn the key dictionary into a list, to be able to iterate over
that list.

This fixes the error:

    RuntimeError: dictionary changed size during iteration