Pinn waitress = 2.1.2 in Python 3.7 and 3.8 to fix robot tests
waitress = 2.1.2 fix the error:

   OSError: [Errno 9] Bad file descriptor

See: https://github.com/Pylons/waitress/issues/374

This error causes the server to "freeze" on robot tests and the tests
never finish.