Issue 745 fix idatetimewidget if ploneappcontenttypes (#748)
* Fix IDatetimeWidget if p.a.contenttypes (#745)

Fix IDatetimeWidget tile override if using plone.app.contenttypes >= 1.1.1:
collective.z3cform.datetimewidget is merged into plone.formwidget.datetime,
so the zcml must override the template from
plone.formwidget.datetime.z3cform.interfaces.IDatetimeWidget as well.

Closes https://github.com/collective/collective.cover/issues/745.

* Try to fix build 269263095.

https://travis-ci.org/collective/collective.cover/builds/269263095

To avoid the errors:

AssertionError: Aug 28, 2017 04:33 PM != Aug 28, 2017 04:31 PM
AssertionError: Aug 28, 2017 04:36 PM != Aug 28, 2017 04:33 PM
AssertionError: Aug 28, 2017 04:33 PM != Aug 28, 2017 04:31 PM

Now we compare the length of the dates instead of the date string
itself.