Wait for tile edit popup to close
Wait before trying to click on another link. We were trying to click on
the link before the popup closed, causing the error:

Test Basic Tile                                                       |
FAIL |
  StaleElementReferenceException: Message: The element reference of <a
class="" href="http://localhost:33931/plone/title-1/?_authenticator=8fe8b900ec8d49c2a19ba16dd97650a9f4309431">
is stale; either the element is no longer attached to the DOM, it is not
in the current frame context, or the document has been refreshed