Try to fix build 269263095.
https://travis-ci.org/collective/collective.cover/builds/269263095

To avoid the errors:

AssertionError: Aug 28, 2017 04:33 PM != Aug 28, 2017 04:31 PM
AssertionError: Aug 28, 2017 04:36 PM != Aug 28, 2017 04:33 PM
AssertionError: Aug 28, 2017 04:33 PM != Aug 28, 2017 04:31 PM

Now we compare the length of the dates instead of the date string
itself.