Fix black-check
click > 8.0.4 causes error on black < 22.3.0:

    ImportError: cannot import name '_unicodefun' from 'click'

See:

https://github.com/psf/black/issues/2964

We can't update the version of black now because black 21.12b0 it is the
last version with python2 support.