Set TZ environment variables in tests to avoid test errors
tzlocal 2.0.0 verifies that the timezone it fouds has the same offset as
the local computer is configured with.If not, it raise the error:

  ValueError: Timezone offset does not match system offset: -7200 !=
-10800. Please, check your config files.

Setting TZ environment variable, this check is no longer done.

Ref: https://github.com/regebro/tzlocal/issues/74